name: Package Resource Pack

on:
  release:
    types: [published]
    
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: assets/ pack.png pack.mcmeta
          dest: Bucket Mobs Resource Pack v${{ github.run_id }}.zip
